In [1]:
import pandas as pd

In [6]:
df=pd.read_csv(r"C:\Users\Alisha\Desktop\Agri_another\Agriculture-data-ML-Based-Attack-Detection\notebooks\data\raw_data\Smart-Farm-IDS.csv")

In [7]:
df.head()

,Timestamp,WaterLevel,WaterPumpToTank,WaterPumpFromTank,WaterTemperature,Ec,Tds,LightIntensity,Humidity,Temperature,HeatIndex,AirQuality,SoilHumidity1,SoilHumidity2,Light,Class
0,14.6.2024 2:0:0,9,Inactive,Inactive,25.88,688.67,256,592.50,58.5,27.3,22.48,476,11.53,13.39,On,Normal
1,14.6.2024 2:0:1,9,Inactive,Inactive,25.88,688.67,256,595.00,58.6,27.3,22.48,475,11.53,13.49,On,Normal
2,14.6.2024 2:0:2,9,Inactive,Inactive,25.88,688.67,256,595.83,58.6,27.3,22.48,476,11.53,13.49,On,Normal
3,14.6.2024 2:0:3,9,Inactive,Inactive,25.88,688.67,256,595.00,58.6,27.3,22.49,475,11.34,13.59,On,Normal
4,14.6.2024 2:0:4,9,Inactive,Inactive,25.88,688.67,256,594.17,58.6,27.3,22.49,475,11.53,13.49,On,Normal

In [8]:
df.columns

Index(['Timestamp', 'WaterLevel', 'WaterPumpToTank', 'WaterPumpFromTank',
       'WaterTemperature', 'Ec', 'Tds', 'LightIntensity', 'Humidity',
       'Temperature', 'HeatIndex', 'AirQuality', 'SoilHumidity1',
       'SoilHumidity2', 'Light', 'Class'],
      dtype='object')

In [9]:
df['Class'].value_counts()

Class
Normal    156252
Attack     16548
Name: count, dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df = df.drop_duplicates()

In [12]:
df.duplicated().sum()

0

Dataset spliting For model Training and Testing Purpose

In [31]:
from sklearn.model_selection import train_test_split
Features_columns=df.iloc[:,:-1]
Target_column=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(Features_columns,Target_column,test_size=0.2,random_state=42,stratify=Target_column)

In [14]:
x_train.shape

(138240, 15)

In [15]:
x_test.shape

(34560, 15)

In [16]:
print("\nTrain class distribution:\n", y_train.value_counts(normalize=True))
print("\nTest class distribution:\n", y_test.value_counts(normalize=True))

Train class distribution:
 Class
Normal    0.904239
Attack    0.095761
Name: proportion, dtype: float64

Test class distribution:
 Class
Normal    0.904225
Attack    0.095775
Name: proportion, dtype: float64

Applying Model BuildIng To the Preproceesd Dataset

Starting with model 1 :

**LogisticRegression**

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
logistic_regrestion_model=LogisticRegression(max_iter=1000)

In [36]:
logistic_regrestion_model.fit(x_train,y_train)

c:\Users\Alisha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [26]:
x_train.dtypes

WaterLevel             int64
WaterPumpToTank        int32
WaterPumpFromTank      int32
WaterTemperature     float64
Ec                   float64
Tds                    int64
LightIntensity       float64
Humidity             float64
Temperature          float64
HeatIndex            float64
AirQuality             int64
SoilHumidity1        float64
SoilHumidity2        float64
Light                  int32
dtype: object

In [33]:
# Preprocess string columns
from sklearn.preprocessing import LabelEncoder
le_X = LabelEncoder()

# Check values for object columns
for col in ['WaterPumpToTank', 'WaterPumpFromTank', 'Light']:
    if col in x_train.columns:
        x_train[col] = le_X.fit_transform(x_train[col])
        x_test[col] = le_X.transform(x_test[col])

# Drop Timestamp
if 'Timestamp' in x_train.columns:
    x_train = x_train.drop('Timestamp', axis=1)
if 'Timestamp' in x_test.columns:
    x_test = x_test.drop('Timestamp', axis=1)

# Ensure y_train and y_test are numeric
le_y = LabelEncoder()
y_train = le_y.fit_transform(y_train)
y_test = le_y.transform(y_test)

x_train.dtypes

WaterLevel             int64
WaterPumpToTank        int64
WaterPumpFromTank      int64
WaterTemperature     float64
Ec                   float64
Tds                    int64
LightIntensity       float64
Humidity             float64
Temperature          float64
HeatIndex            float64
AirQuality             int64
SoilHumidity1        float64
SoilHumidity2        float64
Light                  int64
dtype: object

In [38]:
predicted_values_logistic_regrestion=logistic_regrestion_model.predict(x_test)

In [35]:
predicted_values_logistic_regrestion

array(['Normal', 'Normal', 'Normal', ..., 'Normal', 'Normal', 'Normal'],
      dtype=object)

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, roc_auc_score,precision_score,recall_score, matthews_corrcoef

print(f"The Model Scores For the Logistic Regression")
print()
print(f"Accuracy: {accuracy_score(y_test, predicted_values_logistic_regrestion):.4f}")
print(f"F1 Score: {f1_score(y_test, predicted_values_logistic_regrestion):.4f}")
print(f"precision_scoe: {f1_score(y_test, predicted_values_logistic_regrestion):.4f}")
print(f"recall_score: {f1_score(y_test, predicted_values_logistic_regrestion):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, predicted_values_logistic_regrestion):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, predicted_values_logistic_regrestion):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, predicted_values_logistic_regrestion))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predicted_values_logistic_regrestion))

The Model Scores For the Logistic Regression

Accuracy: 0.9555
F1 Score: 0.9760
precision_scoe: 0.9760
recall_score: 0.9760
ROC-AUC: 0.7697
Matthews Corr. Coef.: 0.7138

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.54      0.70      3310
           1       0.95      1.00      0.98     31250

    accuracy                           0.96     34560
   macro avg       0.97      0.77      0.84     34560
weighted avg       0.96      0.96      0.95     34560


Confusion Matrix:
[[ 1787  1523]
 [   16 31234]]

Starting with model 2 :
DecisionTreeClassifier

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [42]:
decision_tree_model=DecisionTreeClassifier()

In [43]:
decision_tree_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [44]:
predicted_values_decision_tree=decision_tree_model.predict(x_test)

In [45]:
print("The model Scores of the Decision Tree Classifier")
print()
print(f"Accuracy: {accuracy_score(y_test, predicted_values_decision_tree):.4f}")
print(f"F1 Score: {f1_score(y_test, predicted_values_decision_tree):.4f}")
print(f"precision_scoe: {f1_score(y_test, predicted_values_decision_tree):.4f}")
print(f"recall_score: {f1_score(y_test, predicted_values_decision_tree):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, predicted_values_decision_tree):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, predicted_values_decision_tree):.4f}")
print()
print("Classification_report",classification_report(y_test,predicted_values_decision_tree))
print("Confustion matrix",confusion_matrix(y_test,predicted_values_decision_tree))

The model Scores of the Decision Tree Classifier

Accuracy: 0.9998
F1 Score: 0.9999
precision_scoe: 0.9999
recall_score: 0.9999
ROC-AUC: 0.9993
Matthews Corr. Coef.: 0.9988

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3310
           1       1.00      1.00      1.00     31250

    accuracy                           1.00     34560
   macro avg       1.00      1.00      1.00     34560
weighted avg       1.00      1.00      1.00     34560

Confustion matrix [[ 3306     4]
 [    3 31247]]

In [46]:
from sklearn.metrics import accuracy_score

train_pred = decision_tree_model.predict(x_train)

print(accuracy_score(y_train,train_pred))

0.9999927662037037

In [47]:
print("Depth of decision Tree",decision_tree_model.get_depth())
print("Leaves of decision Tree",decision_tree_model.get_n_leaves())

Depth of decision Tree 28
Leaves of decision Tree 146

Starting with model 3 :

RandomForestClassifier

In [48]:
from sklearn.ensemble import RandomForestClassifier

In [49]:
random_forest_model=RandomForestClassifier()

In [50]:
random_forest_model.fit(x_train,y_train)

RandomForestClassifier()

In [51]:
prediction_random_forest=random_forest_model.predict(x_test)

In [52]:
prediction_random_forest

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [53]:
print("The model Scores of the Random Forest Classifier")
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_random_forest):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_random_forest):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_random_forest):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_random_forest):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_random_forest):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_random_forest):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_random_forest))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_random_forest))

The model Scores of the Random Forest Classifier

Accuracy: 0.9997
F1 Score: 0.9998
precision_scoe: 0.9998
recall_score: 0.9998
ROC-AUC: 0.9986
Matthews Corr. Coef.: 0.9983

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3310
           1       1.00      1.00      1.00     31250

    accuracy                           1.00     34560
   macro avg       1.00      1.00      1.00     34560
weighted avg       1.00      1.00      1.00     34560


Confustion matrix [[ 3301     9]
 [    1 31249]]

In [ ]:
importance = pd.Series(random_forest_model.feature_importances_,index=x_train.columns).sort_values(ascending=False)
print(importance)

ValueError: Length of values (14) does not match length of index (15)

Starting with model 4 :

XGBClassifier

In [ ]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgboost_model=XGBClassifier()

In [ ]:
xgboost_model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
prediction_xgboost=xgboost_model.predict(x_test)

In [ ]:
prediction_xgboost

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
print("The model Scores of the XGBClassifier")
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_xgboost):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_xgboost):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_xgboost):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_xgboost):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_xgboost):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_xgboost):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_xgboost))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_xgboost))

The model Scores of the XGBClassifier

Accuracy: 0.9996
F1 Score: 0.9998
precision_scoe: 0.9998
recall_score: 0.9998
ROC-AUC: 0.9989
Matthews Corr. Coef.: 0.9980

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confustion matrix [[ 2815     6]
 [    4 25282]]

In [ ]:
!pip install lightgbm
from lightgbm import LGBMClassifier

Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.16.3)

In [ ]:
lightgbm_model = LGBMClassifier()

In [ ]:
lightgbm_model.fit(x_train, y_train)

[LightGBM] [Info] Number of positive: 101142, number of negative: 11282
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016528 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1771
[LightGBM] [Info] Number of data points in the train set: 112424, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.899648 -> initscore=2.193317
[LightGBM] [Info] Start training from score 2.193317

LGBMClassifier()

In [ ]:
prediction_lightgbm=lightgbm_model.predict(x_test)
print(prediction_lightgbm)

[1 1 1 ... 1 1 1]

In [ ]:
print("Scores of the LightGBM Classifier")
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_lightgbm):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_lightgbm):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_lightgbm):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_lightgbm):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_lightgbm):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_lightgbm):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_lightgbm))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_lightgbm))

Scores of the LightGBM Classifier

Accuracy: 0.9996
F1 Score: 0.9998
precision_scoe: 0.9998
recall_score: 0.9998
ROC-AUC: 0.9987
Matthews Corr. Coef.: 0.9978

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confustion matrix [[ 2814     7]
 [    4 25282]]

In [ ]:
!pip install catboost
from catboost import CatBoostClassifier

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [ ]:
catboost_model=CatBoostClassifier()

In [ ]:
catboost_model.fit(x_train,y_train)

Learning rate set to 0.077384
0:	learn: 0.5994960	total: 154ms	remaining: 2m 33s
1:	learn: 0.5055776	total: 360ms	remaining: 2m 59s
2:	learn: 0.4458196	total: 500ms	remaining: 2m 46s
3:	learn: 0.3779065	total: 628ms	remaining: 2m 36s
4:	learn: 0.3331839	total: 765ms	remaining: 2m 32s
5:	learn: 0.2900307	total: 926ms	remaining: 2m 33s
6:	learn: 0.2632159	total: 1.09s	remaining: 2m 34s
7:	learn: 0.2377863	total: 1.23s	remaining: 2m 33s
8:	learn: 0.2046354	total: 1.43s	remaining: 2m 37s
9:	learn: 0.1906329	total: 1.61s	remaining: 2m 39s
10:	learn: 0.1723538	total: 1.81s	remaining: 2m 43s
11:	learn: 0.1559432	total: 2.04s	remaining: 2m 47s
12:	learn: 0.1427943	total: 2.22s	remaining: 2m 48s
13:	learn: 0.1341304	total: 2.4s	remaining: 2m 48s
14:	learn: 0.1257675	total: 2.57s	remaining: 2m 49s
15:	learn: 0.1104498	total: 2.63s	remaining: 2m 41s
16:	learn: 0.1026047	total: 2.74s	remaining: 2m 38s
17:	learn: 0.0910057	total: 2.85s	remaining: 2m 35s
18:	learn: 0.0816824	total: 2.91s	remaining: 2m 30s
19:	learn: 0.0736188	total: 3s	remaining: 2m 26s
20:	learn: 0.0698534	total: 3.17s	remaining: 2m 27s
21:	learn: 0.0668841	total: 3.29s	remaining: 2m 26s
22:	learn: 0.0638558	total: 3.35s	remaining: 2m 22s
23:	learn: 0.0573574	total: 3.48s	remaining: 2m 21s
24:	learn: 0.0547536	total: 3.58s	remaining: 2m 19s
25:	learn: 0.0496541	total: 3.67s	remaining: 2m 17s
26:	learn: 0.0478849	total: 3.77s	remaining: 2m 15s
27:	learn: 0.0460036	total: 3.92s	remaining: 2m 16s
28:	learn: 0.0420166	total: 4.12s	remaining: 2m 17s
29:	learn: 0.0383213	total: 4.29s	remaining: 2m 18s
30:	learn: 0.0354608	total: 4.56s	remaining: 2m 22s
31:	learn: 0.0339487	total: 4.78s	remaining: 2m 24s
32:	learn: 0.0326104	total: 5.13s	remaining: 2m 30s
33:	learn: 0.0315813	total: 5.42s	remaining: 2m 33s
34:	learn: 0.0302735	total: 5.71s	remaining: 2m 37s
35:	learn: 0.0293034	total: 5.93s	remaining: 2m 38s
36:	learn: 0.0279650	total: 6.27s	remaining: 2m 43s
37:	learn: 0.0263201	total: 6.66s	remaining: 2m 48s
38:	learn: 0.0257154	total: 6.98s	remaining: 2m 52s
39:	learn: 0.0246991	total: 7.31s	remaining: 2m 55s
40:	learn: 0.0231104	total: 7.58s	remaining: 2m 57s
41:	learn: 0.0223703	total: 7.86s	remaining: 2m 59s
42:	learn: 0.0218632	total: 8.07s	remaining: 2m 59s
43:	learn: 0.0210425	total: 8.2s	remaining: 2m 58s
44:	learn: 0.0206094	total: 8.34s	remaining: 2m 57s
45:	learn: 0.0194983	total: 8.54s	remaining: 2m 57s
46:	learn: 0.0188914	total: 8.7s	remaining: 2m 56s
47:	learn: 0.0174883	total: 8.85s	remaining: 2m 55s
48:	learn: 0.0169644	total: 8.96s	remaining: 2m 53s
49:	learn: 0.0164468	total: 9.1s	remaining: 2m 52s
50:	learn: 0.0160080	total: 9.26s	remaining: 2m 52s
51:	learn: 0.0154769	total: 9.5s	remaining: 2m 53s
52:	learn: 0.0147971	total: 9.65s	remaining: 2m 52s
53:	learn: 0.0143456	total: 9.93s	remaining: 2m 53s
54:	learn: 0.0138296	total: 10.1s	remaining: 2m 53s
55:	learn: 0.0135875	total: 10.3s	remaining: 2m 53s
56:	learn: 0.0129676	total: 10.5s	remaining: 2m 53s
57:	learn: 0.0126936	total: 10.8s	remaining: 2m 54s
58:	learn: 0.0125256	total: 11s	remaining: 2m 55s
59:	learn: 0.0123141	total: 11.2s	remaining: 2m 55s
60:	learn: 0.0118078	total: 11.4s	remaining: 2m 55s
61:	learn: 0.0115944	total: 11.5s	remaining: 2m 54s
62:	learn: 0.0114417	total: 11.7s	remaining: 2m 54s
63:	learn: 0.0108934	total: 11.9s	remaining: 2m 53s
64:	learn: 0.0106770	total: 12.1s	remaining: 2m 53s
65:	learn: 0.0101807	total: 12.2s	remaining: 2m 52s
66:	learn: 0.0099630	total: 12.4s	remaining: 2m 52s
67:	learn: 0.0097947	total: 12.5s	remaining: 2m 51s
68:	learn: 0.0095848	total: 12.7s	remaining: 2m 50s
69:	learn: 0.0094947	total: 12.8s	remaining: 2m 50s
70:	learn: 0.0092837	total: 12.9s	remaining: 2m 49s
71:	learn: 0.0089047	total: 13.1s	remaining: 2m 49s
72:	learn: 0.0086446	total: 13.2s	remaining: 2m 48s
73:	learn: 0.0085486	total: 13.4s	remaining: 2m 47s
74:	learn: 0.0084216	total: 13.6s	remaining: 2m 47s
75:	learn: 0.0083248	total: 13.8s	remaining: 2m 47s
76:	learn: 0.0082503	total: 14s	remaining: 2m 47s
77:	learn: 0.0081535	total: 14.2s	remaining: 2m 48s
78:	learn: 0.0080801	total: 14.4s	remaining: 2m 47s
79:	learn: 0.0079798	total: 14.5s	remaining: 2m 47s
80:	learn: 0.0079118	total: 14.7s	remaining: 2m 46s
81:	learn: 0.0078122	total: 14.9s	remaining: 2m 47s
82:	learn: 0.0077677	total: 15s	remaining: 2m 46s
83:	learn: 0.0077333	total: 15.2s	remaining: 2m 45s
84:	learn: 0.0076927	total: 15.3s	remaining: 2m 45s
85:	learn: 0.0076346	total: 15.4s	remaining: 2m 43s
86:	learn: 0.0074624	total: 15.6s	remaining: 2m 43s
87:	learn: 0.0074287	total: 15.8s	remaining: 2m 44s
88:	learn: 0.0073519	total: 16s	remaining: 2m 43s
89:	learn: 0.0070677	total: 16.2s	remaining: 2m 43s
90:	learn: 0.0070190	total: 16.3s	remaining: 2m 42s
91:	learn: 0.0067987	total: 16.5s	remaining: 2m 43s
92:	learn: 0.0067227	total: 16.7s	remaining: 2m 43s
93:	learn: 0.0066879	total: 16.9s	remaining: 2m 43s
94:	learn: 0.0065109	total: 17s	remaining: 2m 42s
95:	learn: 0.0064810	total: 17.1s	remaining: 2m 41s
96:	learn: 0.0064481	total: 17.2s	remaining: 2m 40s
97:	learn: 0.0063117	total: 17.3s	remaining: 2m 39s
98:	learn: 0.0062591	total: 17.5s	remaining: 2m 39s
99:	learn: 0.0061958	total: 17.7s	remaining: 2m 39s
100:	learn: 0.0060738	total: 17.9s	remaining: 2m 39s
101:	learn: 0.0060470	total: 18.2s	remaining: 2m 40s
102:	learn: 0.0059036	total: 18.5s	remaining: 2m 40s
103:	learn: 0.0058179	total: 18.7s	remaining: 2m 41s
104:	learn: 0.0057921	total: 19.1s	remaining: 2m 42s
105:	learn: 0.0057625	total: 19.3s	remaining: 2m 42s
106:	learn: 0.0057309	total: 19.6s	remaining: 2m 43s
107:	learn: 0.0056944	total: 20s	remaining: 2m 45s
108:	learn: 0.0056505	total: 20.2s	remaining: 2m 45s
109:	learn: 0.0056242	total: 20.6s	remaining: 2m 46s
110:	learn: 0.0055738	total: 21s	remaining: 2m 47s
111:	learn: 0.0055159	total: 21.3s	remaining: 2m 49s
112:	learn: 0.0054907	total: 21.7s	remaining: 2m 50s
113:	learn: 0.0054325	total: 22s	remaining: 2m 51s
114:	learn: 0.0053779	total: 22.3s	remaining: 2m 51s
115:	learn: 0.0053475	total: 22.7s	remaining: 2m 52s
116:	learn: 0.0052967	total: 23s	remaining: 2m 53s
117:	learn: 0.0052001	total: 23.3s	remaining: 2m 53s
118:	learn: 0.0051451	total: 23.6s	remaining: 2m 54s
119:	learn: 0.0050615	total: 23.9s	remaining: 2m 55s
120:	learn: 0.0050430	total: 24.1s	remaining: 2m 55s
121:	learn: 0.0050197	total: 24.3s	remaining: 2m 54s
122:	learn: 0.0049762	total: 24.5s	remaining: 2m 54s
123:	learn: 0.0049360	total: 24.7s	remaining: 2m 54s
124:	learn: 0.0048419	total: 24.9s	remaining: 2m 54s
125:	learn: 0.0048419	total: 25s	remaining: 2m 53s
126:	learn: 0.0048419	total: 25.1s	remaining: 2m 52s
127:	learn: 0.0047811	total: 25.4s	remaining: 2m 52s
128:	learn: 0.0047434	total: 25.6s	remaining: 2m 53s
129:	learn: 0.0046982	total: 25.8s	remaining: 2m 52s
130:	learn: 0.0046247	total: 26s	remaining: 2m 52s
131:	learn: 0.0046247	total: 26.2s	remaining: 2m 52s
132:	learn: 0.0046078	total: 26.4s	remaining: 2m 52s
133:	learn: 0.0045692	total: 26.6s	remaining: 2m 52s
134:	learn: 0.0045412	total: 26.8s	remaining: 2m 51s
135:	learn: 0.0044726	total: 26.9s	remaining: 2m 51s
136:	learn: 0.0044435	total: 27.2s	remaining: 2m 51s
137:	learn: 0.0044244	total: 27.4s	remaining: 2m 51s
138:	learn: 0.0044077	total: 27.6s	remaining: 2m 51s
139:	learn: 0.0043615	total: 27.8s	remaining: 2m 50s
140:	learn: 0.0043615	total: 27.9s	remaining: 2m 50s
141:	learn: 0.0043342	total: 28s	remaining: 2m 49s
142:	learn: 0.0043148	total: 28.1s	remaining: 2m 48s
143:	learn: 0.0043148	total: 28.2s	remaining: 2m 47s
144:	learn: 0.0043148	total: 28.3s	remaining: 2m 46s
145:	learn: 0.0043148	total: 28.5s	remaining: 2m 46s
146:	learn: 0.0042946	total: 28.8s	remaining: 2m 47s
147:	learn: 0.0042823	total: 29s	remaining: 2m 47s
148:	learn: 0.0042823	total: 29.2s	remaining: 2m 46s
149:	learn: 0.0042654	total: 29.4s	remaining: 2m 46s
150:	learn: 0.0042232	total: 29.6s	remaining: 2m 46s
151:	learn: 0.0041995	total: 29.7s	remaining: 2m 45s
152:	learn: 0.0041753	total: 29.8s	remaining: 2m 44s
153:	learn: 0.0041171	total: 29.9s	remaining: 2m 44s
154:	learn: 0.0040543	total: 30.1s	remaining: 2m 44s
155:	learn: 0.0040009	total: 30.3s	remaining: 2m 43s
156:	learn: 0.0039497	total: 30.5s	remaining: 2m 43s
157:	learn: 0.0039028	total: 30.7s	remaining: 2m 43s
158:	learn: 0.0038827	total: 30.9s	remaining: 2m 43s
159:	learn: 0.0038582	total: 31.1s	remaining: 2m 43s
160:	learn: 0.0038292	total: 31.2s	remaining: 2m 42s
161:	learn: 0.0037858	total: 31.5s	remaining: 2m 42s
162:	learn: 0.0037633	total: 31.7s	remaining: 2m 42s
163:	learn: 0.0037633	total: 31.9s	remaining: 2m 42s
164:	learn: 0.0037377	total: 32s	remaining: 2m 42s
165:	learn: 0.0037027	total: 32.2s	remaining: 2m 41s
166:	learn: 0.0037027	total: 32.3s	remaining: 2m 41s
167:	learn: 0.0036477	total: 32.4s	remaining: 2m 40s
168:	learn: 0.0036144	total: 32.5s	remaining: 2m 39s
169:	learn: 0.0036144	total: 32.7s	remaining: 2m 39s
170:	learn: 0.0036144	total: 32.8s	remaining: 2m 38s
171:	learn: 0.0036143	total: 32.9s	remaining: 2m 38s
172:	learn: 0.0036143	total: 33.1s	remaining: 2m 38s
173:	learn: 0.0036035	total: 33.3s	remaining: 2m 38s
174:	learn: 0.0036035	total: 33.5s	remaining: 2m 37s
175:	learn: 0.0035722	total: 33.7s	remaining: 2m 37s
176:	learn: 0.0035722	total: 33.9s	remaining: 2m 37s
177:	learn: 0.0035722	total: 34.1s	remaining: 2m 37s
178:	learn: 0.0035722	total: 34.3s	remaining: 2m 37s
179:	learn: 0.0035722	total: 34.5s	remaining: 2m 37s
180:	learn: 0.0035722	total: 34.7s	remaining: 2m 36s
181:	learn: 0.0035721	total: 34.9s	remaining: 2m 36s
182:	learn: 0.0035721	total: 35.1s	remaining: 2m 36s
183:	learn: 0.0035721	total: 35.3s	remaining: 2m 36s
184:	learn: 0.0035721	total: 35.4s	remaining: 2m 36s
185:	learn: 0.0035721	total: 35.6s	remaining: 2m 35s
186:	learn: 0.0035721	total: 35.9s	remaining: 2m 36s
187:	learn: 0.0035721	total: 36.1s	remaining: 2m 35s
188:	learn: 0.0035720	total: 36.3s	remaining: 2m 35s
189:	learn: 0.0035720	total: 36.5s	remaining: 2m 35s
190:	learn: 0.0035720	total: 36.8s	remaining: 2m 35s
191:	learn: 0.0035720	total: 37s	remaining: 2m 35s
192:	learn: 0.0035720	total: 37.1s	remaining: 2m 35s
193:	learn: 0.0035719	total: 37.3s	remaining: 2m 34s
194:	learn: 0.0035719	total: 37.4s	remaining: 2m 34s
195:	learn: 0.0035720	total: 37.5s	remaining: 2m 34s
196:	learn: 0.0035720	total: 37.7s	remaining: 2m 33s
197:	learn: 0.0035719	total: 37.7s	remaining: 2m 32s
198:	learn: 0.0035719	total: 37.9s	remaining: 2m 32s
199:	learn: 0.0035719	total: 38s	remaining: 2m 31s
200:	learn: 0.0035719	total: 38.1s	remaining: 2m 31s
201:	learn: 0.0035719	total: 38.1s	remaining: 2m 30s
202:	learn: 0.0035719	total: 38.2s	remaining: 2m 30s
203:	learn: 0.0035719	total: 38.3s	remaining: 2m 29s
204:	learn: 0.0035719	total: 38.4s	remaining: 2m 28s
205:	learn: 0.0035719	total: 38.5s	remaining: 2m 28s
206:	learn: 0.0035719	total: 38.6s	remaining: 2m 27s
207:	learn: 0.0035718	total: 38.7s	remaining: 2m 27s
208:	learn: 0.0035718	total: 38.8s	remaining: 2m 27s
209:	learn: 0.0035718	total: 39s	remaining: 2m 26s
210:	learn: 0.0035718	total: 39.1s	remaining: 2m 26s
211:	learn: 0.0035718	total: 39.2s	remaining: 2m 25s
212:	learn: 0.0035718	total: 39.4s	remaining: 2m 25s
213:	learn: 0.0035718	total: 39.5s	remaining: 2m 25s
214:	learn: 0.0035718	total: 39.6s	remaining: 2m 24s
215:	learn: 0.0035718	total: 39.7s	remaining: 2m 24s
216:	learn: 0.0035718	total: 39.8s	remaining: 2m 23s
217:	learn: 0.0035718	total: 39.9s	remaining: 2m 23s
218:	learn: 0.0035718	total: 40s	remaining: 2m 22s
219:	learn: 0.0035718	total: 40.1s	remaining: 2m 22s
220:	learn: 0.0035718	total: 40.2s	remaining: 2m 21s
221:	learn: 0.0035718	total: 40.3s	remaining: 2m 21s
222:	learn: 0.0035718	total: 40.4s	remaining: 2m 20s
223:	learn: 0.0035718	total: 40.4s	remaining: 2m 20s
224:	learn: 0.0035718	total: 40.5s	remaining: 2m 19s
225:	learn: 0.0035718	total: 40.6s	remaining: 2m 19s
226:	learn: 0.0035718	total: 40.7s	remaining: 2m 18s
227:	learn: 0.0035718	total: 40.9s	remaining: 2m 18s
228:	learn: 0.0035718	total: 41.1s	remaining: 2m 18s
229:	learn: 0.0035718	total: 41.2s	remaining: 2m 18s
230:	learn: 0.0035718	total: 41.4s	remaining: 2m 17s
231:	learn: 0.0035718	total: 41.5s	remaining: 2m 17s
232:	learn: 0.0035718	total: 41.6s	remaining: 2m 17s
233:	learn: 0.0035718	total: 41.8s	remaining: 2m 16s
234:	learn: 0.0035718	total: 41.9s	remaining: 2m 16s
235:	learn: 0.0035718	total: 42s	remaining: 2m 16s
236:	learn: 0.0035717	total: 42.2s	remaining: 2m 15s
237:	learn: 0.0035717	total: 42.3s	remaining: 2m 15s
238:	learn: 0.0035717	total: 42.4s	remaining: 2m 15s
239:	learn: 0.0035717	total: 42.5s	remaining: 2m 14s
240:	learn: 0.0035717	total: 42.6s	remaining: 2m 14s
241:	learn: 0.0035717	total: 42.7s	remaining: 2m 13s
242:	learn: 0.0035717	total: 42.8s	remaining: 2m 13s
243:	learn: 0.0035717	total: 42.9s	remaining: 2m 12s
244:	learn: 0.0035717	total: 43s	remaining: 2m 12s
245:	learn: 0.0035717	total: 43s	remaining: 2m 11s
246:	learn: 0.0035717	total: 43.1s	remaining: 2m 11s
247:	learn: 0.0035717	total: 43.1s	remaining: 2m 10s
248:	learn: 0.0035717	total: 43.2s	remaining: 2m 10s
249:	learn: 0.0035717	total: 43.2s	remaining: 2m 9s
250:	learn: 0.0035717	total: 43.3s	remaining: 2m 9s
251:	learn: 0.0035717	total: 43.3s	remaining: 2m 8s
252:	learn: 0.0035717	total: 43.4s	remaining: 2m 8s
253:	learn: 0.0035717	total: 43.5s	remaining: 2m 7s
254:	learn: 0.0035717	total: 43.6s	remaining: 2m 7s
255:	learn: 0.0035717	total: 43.6s	remaining: 2m 6s
256:	learn: 0.0035717	total: 43.7s	remaining: 2m 6s
257:	learn: 0.0035717	total: 43.8s	remaining: 2m 6s
258:	learn: 0.0035717	total: 43.9s	remaining: 2m 5s
259:	learn: 0.0035717	total: 43.9s	remaining: 2m 5s
260:	learn: 0.0035717	total: 44s	remaining: 2m 4s
261:	learn: 0.0035717	total: 44s	remaining: 2m 4s
262:	learn: 0.0035717	total: 44.1s	remaining: 2m 3s
263:	learn: 0.0035717	total: 44.2s	remaining: 2m 3s
264:	learn: 0.0035717	total: 44.3s	remaining: 2m 2s
265:	learn: 0.0035717	total: 44.4s	remaining: 2m 2s
266:	learn: 0.0035717	total: 44.4s	remaining: 2m 1s
267:	learn: 0.0035717	total: 44.5s	remaining: 2m 1s
268:	learn: 0.0035717	total: 44.5s	remaining: 2m
269:	learn: 0.0035717	total: 44.6s	remaining: 2m
270:	learn: 0.0035717	total: 44.6s	remaining: 2m
271:	learn: 0.0035717	total: 44.7s	remaining: 1m 59s
272:	learn: 0.0035717	total: 44.7s	remaining: 1m 59s
273:	learn: 0.0035717	total: 44.8s	remaining: 1m 58s
274:	learn: 0.0035717	total: 44.8s	remaining: 1m 58s
275:	learn: 0.0035717	total: 44.9s	remaining: 1m 57s
276:	learn: 0.0035717	total: 44.9s	remaining: 1m 57s
277:	learn: 0.0035717	total: 45s	remaining: 1m 56s
278:	learn: 0.0035717	total: 45s	remaining: 1m 56s
279:	learn: 0.0035717	total: 45.1s	remaining: 1m 55s
280:	learn: 0.0035717	total: 45.1s	remaining: 1m 55s
281:	learn: 0.0035717	total: 45.2s	remaining: 1m 54s
282:	learn: 0.0035717	total: 45.2s	remaining: 1m 54s
283:	learn: 0.0035717	total: 45.3s	remaining: 1m 54s
284:	learn: 0.0035717	total: 45.4s	remaining: 1m 53s
285:	learn: 0.0035717	total: 45.4s	remaining: 1m 53s
286:	learn: 0.0035717	total: 45.5s	remaining: 1m 53s
287:	learn: 0.0035717	total: 45.6s	remaining: 1m 52s
288:	learn: 0.0035717	total: 45.7s	remaining: 1m 52s
289:	learn: 0.0035717	total: 45.7s	remaining: 1m 51s
290:	learn: 0.0035717	total: 45.8s	remaining: 1m 51s
291:	learn: 0.0035717	total: 45.8s	remaining: 1m 51s
292:	learn: 0.0035717	total: 45.9s	remaining: 1m 50s
293:	learn: 0.0035717	total: 45.9s	remaining: 1m 50s
294:	learn: 0.0035717	total: 46s	remaining: 1m 49s
295:	learn: 0.0035717	total: 46s	remaining: 1m 49s
296:	learn: 0.0035717	total: 46.1s	remaining: 1m 49s
297:	learn: 0.0035717	total: 46.1s	remaining: 1m 48s
298:	learn: 0.0035717	total: 46.2s	remaining: 1m 48s
299:	learn: 0.0035717	total: 46.3s	remaining: 1m 48s
300:	learn: 0.0035717	total: 46.4s	remaining: 1m 47s
301:	learn: 0.0035717	total: 46.4s	remaining: 1m 47s
302:	learn: 0.0035717	total: 46.4s	remaining: 1m 46s
303:	learn: 0.0035717	total: 46.5s	remaining: 1m 46s
304:	learn: 0.0035717	total: 46.5s	remaining: 1m 45s
305:	learn: 0.0035717	total: 46.6s	remaining: 1m 45s
306:	learn: 0.0035717	total: 46.6s	remaining: 1m 45s
307:	learn: 0.0035717	total: 46.7s	remaining: 1m 44s
308:	learn: 0.0035717	total: 46.7s	remaining: 1m 44s
309:	learn: 0.0035717	total: 46.8s	remaining: 1m 44s
310:	learn: 0.0035717	total: 46.9s	remaining: 1m 43s
311:	learn: 0.0035717	total: 47s	remaining: 1m 43s
312:	learn: 0.0035717	total: 47s	remaining: 1m 43s
313:	learn: 0.0035717	total: 47.1s	remaining: 1m 42s
314:	learn: 0.0035717	total: 47.1s	remaining: 1m 42s
315:	learn: 0.0035717	total: 47.2s	remaining: 1m 42s
316:	learn: 0.0035717	total: 47.3s	remaining: 1m 41s
317:	learn: 0.0035717	total: 47.3s	remaining: 1m 41s
318:	learn: 0.0035717	total: 47.5s	remaining: 1m 41s
319:	learn: 0.0035717	total: 47.6s	remaining: 1m 41s
320:	learn: 0.0035717	total: 47.6s	remaining: 1m 40s
321:	learn: 0.0035717	total: 47.7s	remaining: 1m 40s
322:	learn: 0.0035717	total: 47.8s	remaining: 1m 40s
323:	learn: 0.0035717	total: 47.8s	remaining: 1m 39s
324:	learn: 0.0035717	total: 47.8s	remaining: 1m 39s
325:	learn: 0.0035717	total: 47.9s	remaining: 1m 38s
326:	learn: 0.0035717	total: 48s	remaining: 1m 38s
327:	learn: 0.0035717	total: 48s	remaining: 1m 38s
328:	learn: 0.0035716	total: 48.1s	remaining: 1m 38s
329:	learn: 0.0035716	total: 48.2s	remaining: 1m 37s
330:	learn: 0.0035716	total: 48.3s	remaining: 1m 37s
331:	learn: 0.0035716	total: 48.4s	remaining: 1m 37s
332:	learn: 0.0035716	total: 48.5s	remaining: 1m 37s
333:	learn: 0.0035716	total: 48.5s	remaining: 1m 36s
334:	learn: 0.0035716	total: 48.6s	remaining: 1m 36s
335:	learn: 0.0035716	total: 48.7s	remaining: 1m 36s
336:	learn: 0.0035716	total: 48.8s	remaining: 1m 35s
337:	learn: 0.0035716	total: 48.9s	remaining: 1m 35s
338:	learn: 0.0035716	total: 48.9s	remaining: 1m 35s
339:	learn: 0.0035716	total: 49s	remaining: 1m 35s
340:	learn: 0.0035716	total: 49.1s	remaining: 1m 34s
341:	learn: 0.0035716	total: 49.2s	remaining: 1m 34s
342:	learn: 0.0035716	total: 49.3s	remaining: 1m 34s
343:	learn: 0.0035716	total: 49.4s	remaining: 1m 34s
344:	learn: 0.0035716	total: 49.4s	remaining: 1m 33s
345:	learn: 0.0035716	total: 49.5s	remaining: 1m 33s
346:	learn: 0.0035716	total: 49.6s	remaining: 1m 33s
347:	learn: 0.0035716	total: 49.6s	remaining: 1m 32s
348:	learn: 0.0035716	total: 49.7s	remaining: 1m 32s
349:	learn: 0.0035716	total: 49.7s	remaining: 1m 32s
350:	learn: 0.0035716	total: 49.8s	remaining: 1m 32s
351:	learn: 0.0035716	total: 49.9s	remaining: 1m 31s
352:	learn: 0.0035716	total: 50s	remaining: 1m 31s
353:	learn: 0.0035716	total: 50s	remaining: 1m 31s
354:	learn: 0.0035716	total: 50.1s	remaining: 1m 31s
355:	learn: 0.0035716	total: 50.2s	remaining: 1m 30s
356:	learn: 0.0035716	total: 50.2s	remaining: 1m 30s
357:	learn: 0.0035716	total: 50.3s	remaining: 1m 30s
358:	learn: 0.0035716	total: 50.4s	remaining: 1m 29s
359:	learn: 0.0035716	total: 50.5s	remaining: 1m 29s
360:	learn: 0.0035716	total: 50.6s	remaining: 1m 29s
361:	learn: 0.0035716	total: 50.7s	remaining: 1m 29s
362:	learn: 0.0035716	total: 50.8s	remaining: 1m 29s
363:	learn: 0.0035716	total: 50.8s	remaining: 1m 28s
364:	learn: 0.0035716	total: 50.9s	remaining: 1m 28s
365:	learn: 0.0035716	total: 51s	remaining: 1m 28s
366:	learn: 0.0035716	total: 51.1s	remaining: 1m 28s
367:	learn: 0.0035716	total: 51.1s	remaining: 1m 27s
368:	learn: 0.0035716	total: 51.2s	remaining: 1m 27s
369:	learn: 0.0035715	total: 51.2s	remaining: 1m 27s
370:	learn: 0.0035715	total: 51.3s	remaining: 1m 26s
371:	learn: 0.0035715	total: 51.3s	remaining: 1m 26s
372:	learn: 0.0035715	total: 51.4s	remaining: 1m 26s
373:	learn: 0.0035715	total: 51.4s	remaining: 1m 26s
374:	learn: 0.0035715	total: 51.4s	remaining: 1m 25s
375:	learn: 0.0035715	total: 51.5s	remaining: 1m 25s
376:	learn: 0.0035715	total: 51.5s	remaining: 1m 25s
377:	learn: 0.0035715	total: 51.6s	remaining: 1m 24s
378:	learn: 0.0035715	total: 51.7s	remaining: 1m 24s
379:	learn: 0.0035715	total: 51.8s	remaining: 1m 24s

CatBoostClassifier()

In [ ]:
prediction_catboost=catboost_model.predict(x_test)
print(prediction_catboost)

[1 1 1 ... 1 1 1]

In [ ]:
print('The model Scores of the CatBoostClassifier')
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_catboost):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_catboost):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_catboost):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_catboost):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_catboost):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_catboost):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_catboost))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_catboost))

The model Scores of the CatBoostClassifier

Accuracy: 0.9996
F1 Score: 0.9998
precision_scoe: 0.9998
recall_score: 0.9998
ROC-AUC: 0.9979
Matthews Corr. Coef.: 0.9976

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confustion matrix [[ 2809    12]
 [    0 25286]]

Starting with model 4 :

SvmClassifier

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm_model=SVC()

In [ ]:
svm_model.fit(x_train,y_train)

SVC()

In [ ]:
prediction_svm_model=svm_model.predict(x_test)

In [ ]:
print("The scores of the SVM Classifier")
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_svm_model):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_svm_model):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_svm_model):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_svm_model):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_svm_model):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_svm_model):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_svm_model))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_svm_model))

The scores of the SVM Classifier

Accuracy: 0.9026
F1 Score: 0.9487
precision_scoe: 0.9487
recall_score: 0.9487
ROC-AUC: 0.5149
Matthews Corr. Coef.: 0.1639

Classification_report               precision    recall  f1-score   support

           0       1.00      0.03      0.06      2821
           1       0.90      1.00      0.95     25286

    accuracy                           0.90     28107
   macro avg       0.95      0.51      0.50     28107
weighted avg       0.91      0.90      0.86     28107


Confustion matrix [[   84  2737]
 [    0 25286]]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn_model=KNeighborsClassifier()

In [ ]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
prediction_knn=knn_model.predict(x_test)

In [ ]:
print("The scores of the KNN Classifier")
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_knn):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_knn):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_knn):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_knn):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_knn):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_knn):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_knn))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_knn))

The scores of the KNN Classifier

Accuracy: 0.9996
F1 Score: 0.9998
precision_scoe: 0.9998
recall_score: 0.9998
ROC-AUC: 0.9979
Matthews Corr. Coef.: 0.9976

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confustion matrix [[ 2809    12]
 [    0 25286]]

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
adaboost_model = AdaBoostClassifier()

In [ ]:
adaboost_model.fit(x_train, y_train)

AdaBoostClassifier()

In [ ]:
prediction_adaboost = adaboost_model.predict(x_test)

In [ ]:
print('The model Scores of the AdaBoostClassifier')
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_adaboost):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_adaboost):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_adaboost):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_adaboost):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_adaboost):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_adaboost):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_adaboost))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_adaboost))

The model Scores of the AdaBoostClassifier

Accuracy: 0.9188
F1 Score: 0.9566
precision_scoe: 0.9566
recall_score: 0.9566
ROC-AUC: 0.6147
Matthews Corr. Coef.: 0.4190

Classification_report               precision    recall  f1-score   support

           0       0.84      0.23      0.37      2821
           1       0.92      1.00      0.96     25286

    accuracy                           0.92     28107
   macro avg       0.88      0.61      0.66     28107
weighted avg       0.91      0.92      0.90     28107


Confustion matrix [[  661  2160]
 [  122 25164]]

Starting with model 9 :

ExtraTreesClassifier

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
extratrees_model = ExtraTreesClassifier()
extratrees_model.fit(x_train, y_train)

ExtraTreesClassifier()

In [ ]:
prediction_extratrees = extratrees_model.predict(x_test)
print(prediction_extratrees)

[1 1 1 ... 1 1 1]

In [ ]:
print('The model Scores of the ExtraTreesClassifier')
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_extratrees):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_extratrees):.4f}")
print(f"precision_scoe: {f1_score(y_test, prediction_extratrees):.4f}")
print(f"recall_score: {f1_score(y_test, prediction_extratrees):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_extratrees):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_extratrees):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_extratrees))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_extratrees))

The model Scores of the ExtraTreesClassifier

Accuracy: 0.9997
F1 Score: 0.9998
precision_scoe: 0.9998
recall_score: 0.9998
ROC-AUC: 0.9989
Matthews Corr. Coef.: 0.9982

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confustion matrix [[ 2815     6]
 [    3 25283]]

Starting with Model 10 : BaggingClassifier

In [ ]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
bagging_model = BaggingClassifier(random_state=42)
bagging_model.fit(x_train, y_train)

BaggingClassifier(random_state=42)

In [ ]:
prediction_bagging = bagging_model.predict(x_test)
print('The model Scores of the BaggingClassifier')
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_bagging):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_bagging):.4f}")
print(f"precision_scoe: {precision_score(y_test, prediction_bagging):.4f}")
print(f"recall_score: {recall_score(y_test, prediction_bagging):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_bagging):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_bagging):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_bagging))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_bagging))

The model Scores of the BaggingClassifier

Accuracy: 0.9995
F1 Score: 0.9997
precision_scoe: 0.9996
recall_score: 0.9998
ROC-AUC: 0.9983
Matthews Corr. Coef.: 0.9970

Classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confustion matrix [[ 2812     9]
 [    6 25280]]

Starting with model 11 :

GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gradient_boosting_model = GradientBoostingClassifier()
gradient_boosting_model.fit(x_train, y_train)

GradientBoostingClassifier()

In [ ]:
prediction_gradient_boosting = gradient_boosting_model.predict(x_test)
print('The model Scores of the GradientBoostingClassifier')
print()
print(f"Accuracy: {accuracy_score(y_test, prediction_gradient_boosting):.4f}")
print(f"F1 Score: {f1_score(y_test, prediction_gradient_boosting):.4f}")
print(f"precision_scoe: {precision_score(y_test, prediction_gradient_boosting):.4f}")
print(f"recall_score: {recall_score(y_test, prediction_gradient_boosting):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, prediction_gradient_boosting):.4f}")
print(f"Matthews Corr. Coef.: {matthews_corrcoef(y_test, prediction_gradient_boosting):.4f}")
print()
print("Classification_report",classification_report(y_test,prediction_gradient_boosting))
print()
print("Confustion matrix",confusion_matrix(y_test,prediction_gradient_boosting))

The model Scores of the GradientBoostingClassifier

Accuracy: 0.9924
F1 Score: 0.9958
precision_scoe: 0.9916
recall_score: 1.0000
ROC-AUC: 0.9621
Matthews Corr. Coef.: 0.9573

Classification_report               precision    recall  f1-score   support

           0       1.00      0.92      0.96      2821
           1       0.99      1.00      1.00     25286

    accuracy                           0.99     28107
   macro avg       1.00      0.96      0.98     28107
weighted avg       0.99      0.99      0.99     28107


Confustion matrix [[ 2607   214]
 [    0 25286]]

In [ ]:
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    StackingClassifier
)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    matthews_corrcoef
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# ==========================================
# Base Models
# ==========================================

rf = RandomForestClassifier(
    random_state=42
)

et = ExtraTreesClassifier(
    random_state=42
)

xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

lgbm = LGBMClassifier(
    random_state=42
)

# ==========================================
# Meta Model
# ==========================================

meta_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# ==========================================
# Stacking Classifier
# ==========================================

stacking_model = StackingClassifier(
    estimators=[
        ('rf', rf),
        ('et', et),
        ('xgb', xgb),
        ('lgbm', lgbm)
    ],
    final_estimator=meta_model,
    cv=5,
    n_jobs=-1 # Use all available CPU cores
)

# ==========================================
# Train Model
# ==========================================

stacking_model.fit(x_train, y_train)

# ==========================================
# Predictions
# ==========================================

y_pred = stacking_model.predict(x_test)

y_prob = stacking_model.predict_proba(x_test)[:, 1]

# ==========================================
# Evaluation Metrics
# ==========================================

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
mcc = matthews_corrcoef(y_test, y_pred)

print("Accuracy:", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1 Score:", round(f1, 4))
print("ROC-AUC:", round(roc_auc, 4))
print("Matthews Corr. Coef.:", round(mcc, 4))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9997
Precision: 0.9998
Recall: 0.9999
F1 Score: 0.9998
ROC-AUC: 0.9999
Matthews Corr. Coef.: 0.9984

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2821
           1       1.00      1.00      1.00     25286

    accuracy                           1.00     28107
   macro avg       1.00      1.00      1.00     28107
weighted avg       1.00      1.00      1.00     28107


Confusion Matrix:
[[ 2815     6]
 [    2 25284]]

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.corr(numeric_only=True)['Class'].sort_values()

WaterPumpToTank        -0.375580
WaterPumpFromTank      -0.258821
Nutrient_Density       -0.163143
WaterTemperature       -0.094915
WaterLevel             -0.094453
Is_Weekend             -0.079880
DayOfWeek              -0.076296
Is_Night_Time          -0.058383
Hour_cos               -0.053575
Hour_sin               -0.042096
Tds_log                -0.028036
Ec                     -0.016265
HeatIndex              -0.016002
Env_Stress             -0.015256
Avg_Soil_Humidity      -0.003712
Humidity                0.003517
AirQuality              0.025877
LightIntensity          0.033420
Temperature             0.048298
Light                   0.094693
Class                   1.000000
Pump_Status_Mismatch         NaN
Name: Class, dtype: float64

In [ ]:
Features_columns.columns.tolist()

['WaterLevel',
 'WaterPumpToTank',
 'WaterPumpFromTank',
 'WaterTemperature',
 'Ec',
 'LightIntensity',
 'Humidity',
 'Temperature',
 'HeatIndex',
 'AirQuality',
 'Light',
 'Tds_log',
 'Avg_Soil_Humidity',
 'DayOfWeek',
 'Hour_sin',
 'Hour_cos',
 'Is_Night_Time',
 'Is_Weekend',
 'Env_Stress',
 'Nutrient_Density',
 'Pump_Status_Mismatch']